config/routes.rb
Rails.application.routes.draw do
root :to => 'books#books'
get 'books' => 'books#index'
post 'books' => 'books#create'
get 'books/:id' => 'books#show',as: 'book'
get 'books/:id/edit' => 'books#edit', as: 'edit_books'
patch 'books/:id' => 'books#update', as: 'update_books'
delete 'books/:id' => 'books#destroy', as: 'destroy_books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
     # Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
  end

  def edit
    @book = Book.find(params[:id])
    @books = Book.all
  end

  def books
  end

  def create
      @books = Book.all
      @book = Book.new(list_params)
      if @book.save
      flash[:notice] = "Book was successfully destroyed."
      redirect_to book_path(@book.id)
      else
        @books = Book.all
        render 'index'
      end
  end

  def update
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.update(list_params)
    flash[:notice] = "Book was successfully destroyed."
    redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def list_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/books.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や<br/>
印象を共有し交換することができます</p>
<%= link_to 'start','/books' %>

app/views/books/edit.html.erb
<div id="edit-title">
  <div class="edit-logo">
    <h1>Editing Book</h1>
  </div>
   <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
   <%= form_with model:@book,local:true,class: "main-item" do |f| %>
          <% if @book.errors.any? %>
                <h2 class="main-error"><%= @book.errors.count %>個のerrorsがあります<br></h2>
                    <% @book.errors.full_messages.each do |msg| %>
                      <li class="main-error2"><%= msg %><br/></li>
          <% end %>
  <% end %>
  <div class="edit-logo">
    <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
      <div class="edit-title">
        <p>Title</p>
        <%= f.text_field :title %>
      </div>
      <div class="edit-body">
        <p>Body</p>
        <%= f.text_area :body %>
      </div>
      <%= f.submit 'Update Book' %>
    <% end %>
    <% end %>
    <div class="edit-list">
    <%= link_to 'Show', book_path(@book) %>
    <%= link_to 'back','/books' %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
  <!-- form_with部分 -->
   <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
  <% end %>
  <div id="main-title">
    <h1>Books</h1>
  </div>
    <table>
      <thead>
          <tr class="tr-title">
            <th>Title</th>
            <th>body</th>
            <th></th>
          </tr>
      <thead>
          <% @books.each do |book| %>
          <tbody>
            <tr class="tr-tilte2">
              <td class="td-tilte"><span><%= book.title %></span></td>
              <td class="td-title"><span><%= book.body %></span></td>
              <td><%= link_to 'Show', book_path(book) %></td>
              <td><%= link_to 'Edit', edit_books_path(book.id) %></td>
              <td><%= link_to "delete", book_path(book), method: :delete, data:{confirm:'Are you sure?'}%></td>
            </tr>
          </tbody>
           <% end %>
    </table>
    <div class="main-logo">
      <h1>New book</h1>
    </div>
      <%= form_with model:@book,local:true,class: "main-item" do |f| %>
          <% if @book.errors.any? %>
                <h2 class="main-error"><%= @book.errors.count %>個のerrorsがあります<br></h2>
                    <% @book.errors.full_messages.each do |msg| %>
                      <li class="main-error2"><%= msg %><br/></li>
          <% end %>
      <% end %>
            <div class="main-list">
              <h4>title</h4>
              <%= f.text_field :title %>
            </div>
              <div class="main-list2">
                <h4>body</h4>
                <%= f.text_area :body %>
                <%= f.submit 'Create Book' %>
                <% end %>
              </div>
</main>

app/views/books/show.html.erb
<div id="show-title">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <p><span>title:<%= @book.title %></span></p>
    <p><span>body:<%= @book.body %></span></p>
        <div class="show-list">
            <%= link_to "edit", edit_books_path(@book.id) %>
            <%= link_to 'back','/books' %>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>